// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<YOUR_API_KEY>',
    appId: '<YOUR_APP_ID>',
    messagingSenderId: '<YOUR_MESSAGING_SENDER_ID>',
    projectId: '<YOUR_PROJECT_ID>',
    databaseURL: '<YOUR_DATABASE_URL>',
    storageBucket: '<YOUR_STORAGE_BUCKET>',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7OPrF8jUCnVIjHkXTi11yzoaqQFNnTaY',
    appId: '1:556788420487:web:99a9b9f573112e55090d22',
    messagingSenderId: '556788420487',
    projectId: 'mobile-games-2783a',
    authDomain: 'mobile-games-2783a.firebaseapp.com',
    databaseURL: 'https://mobile-games-2783a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-games-2783a.appspot.com',
  );

}